- name: Run Live Environment Audit (Desktop)
        env:
          DATABASE_URL: ${{ secrets.LIVE_DATABASE_URL }}
          PAGESPEED_API_KEY: ${{ secrets.PAGESPEED_API_KEY }}
          TARGET_URL: "https://tow-trust.co.uk"
          AUDIT_STRATEGY: "desktop"
        run: python run_audit.py

      - name: Run Live Environment Audit (Mobile)
        env:
          DATABASE_URL: ${{ secrets.LIVE_DATABASE_URL }}
          PAGESPEED_API_KEY: ${{ secrets.PAGESPEED_API_KEY }}
          TARGET_URL: "https://tow-trust.co.uk"
          AUDIT_STRATEGY: "mobile"
        run: python run_audit.py

      - name: Run Sandbox Environment Audit (Desktop)
        env:
          DATABASE_URL: ${{ secrets.SANDBOX_DATABASE_URL }}
          PAGESPEED_API_KEY: ${{ secrets.PAGESPEED_API_KEY }}
          TARGET_URL: "https://towtrust.cloudfyuat.com"
          AUDIT_STRATEGY: "desktop"
        run: python run_audit.py

      - name: Run Sandbox Environment Audit (Mobile)
        env:
          DATABASE_URL: ${{ secrets.SANDBOX_DATABASE_URL }}
          PAGESPEED_API_KEY: ${{ secrets.PAGESPEED_API_KEY }}
          TARGET_URL: "https://towtrust.cloudfyuat.com"
          AUDIT_STRATEGY: "mobile"
        run: python run_audit.py
